Repository dusk-network/phoenix, pull requests merged in 2020-06, with the labels that each got.

#52 Refactoring type names
  Cargo.toml
  benches/phoenix.rs
  src/crypto/merkle.rs
  src/crypto/mod.rs
  src/crypto/tests.rs
  src/db/mod.rs
  src/db/tests.rs
  src/error.rs
  src/keys/public.rs
  src/keys/secret.rs
  src/keys/tests.rs
  src/keys/view.rs
  src/lib.rs
  src/note/mod.rs
  src/note/nullifier.rs
  src/note/obfuscated.rs
  src/note/tests.rs
  src/note/transparent.rs
  src/note/variant.rs
  src/rpc/tests.rs
  src/rpc/types.rs
  src/transaction/item.rs
  src/transaction/mod.rs
  src/utils.rs
  src/zk/gadgets/balance.rs
  src/zk/gadgets/merkle.rs
  src/zk/gadgets/nullifier.rs
  src/zk/gadgets/preimage.rs
  src/zk/gadgets/sanity.rs
  src/zk/gadgets/sk_r.rs
  src/zk/merkle.rs
  src/zk/mod.rs
  src/zk/public_inputs.rs
  src/zk/tests.rs
  src/zk/transaction.rs
Labels: enhancement, type:refactor

#65 Take Db by reference, not by Path
  src/db/mod.rs
  src/db/tests.rs
  src/keys/tests.rs
  src/note/mod.rs
  src/note/tests.rs
  src/rpc/tests.rs
  src/transaction/item.rs
  src/transaction/mod.rs
  src/zk/gadgets/balance.rs
  src/zk/gadgets/nullifier.rs
  src/zk/tests.rs
Labels: status:blocker, type:refactor

#54 Refactor gadgets
  Cargo.toml
  dusk-protobuf/autogen/go/monitor/monitor.pb.go
  dusk-protobuf/autogen/go/node/mempool.pb.go
  dusk-protobuf/autogen/go/node/node.mock.go
  dusk-protobuf/autogen/go/node/node.pb.go
  dusk-protobuf/autogen/go/node/wallet.pb.go
  dusk-protobuf/autogen/go/rusk/consensus.pb.go
  dusk-protobuf/autogen/go/rusk/field.pb.go
  dusk-protobuf/autogen/go/rusk/github.com/dusk-protobuf/autogen/go/rusk/consensus.pb.go
  dusk-protobuf/autogen/go/rusk/github.com/dusk-protobuf/autogen/go/rusk/rusk.pb.go
  dusk-protobuf/autogen/go/rusk/keys.pb.go
  dusk-protobuf/autogen/go/rusk/note.pb.go
  dusk-protobuf/autogen/go/rusk/rusk.mock.go
  dusk-protobuf/autogen/go/rusk/rusk.pb.go
  dusk-protobuf/autogen/go/rusk/rusk.pb_test.go
  dusk-protobuf/autogen/go/rusk/transaction.pb.go
  dusk-protobuf/node/README.md
  dusk-protobuf/node/mempool.proto
  dusk-protobuf/node/node.proto
  dusk-protobuf/node/wallet.proto
  dusk-protobuf/rusk/README.md
  dusk-protobuf/rusk/consensus.proto
  dusk-protobuf/rusk/field.proto
  dusk-protobuf/rusk/note.proto
  dusk-protobuf/rusk/rusk.proto
  dusk-protobuf/rusk/transaction.proto
  src/crypto/mod.rs
  src/db/tests.rs
  src/note/mod.rs
  src/note/obfuscated.rs
  src/note/tests.rs
  src/note/transparent.rs
  src/note/variant.rs
  src/rpc/tests.rs
  src/rpc/types.rs
  src/transaction/item.rs
  src/transaction/mod.rs
  src/utils.rs
  src/zk/gadgets/balance.rs
  src/zk/gadgets/commitment.rs
  src/zk/gadgets/merkle.rs
  src/zk/gadgets/mod.rs
  src/zk/gadgets/nullifier.rs
  src/zk/gadgets/preimage.rs
  src/zk/gadgets/range.rs
  src/zk/gadgets/sanity.rs
  src/zk/gadgets/sk_r.rs
  src/zk/mod.rs
  src/zk/public_inputs.rs
  src/zk/tests.rs
  src/zk/transaction.rs
Labels: area:cryptography, enhancement, type:refactor
